###Получение списка всех тикетов в короткой форме
GET http://{{host}}/api/tickets/all/shortView
Authorization: Basic {{admin_login}} {{admin_password}}

###Получение списка всех тикетов в полной форме
GET http://{{host}}/api/tickets/all/fullView
Authorization: Basic {{admin_login}} {{admin_password}}

###Получение списка всех тикетов конкретного юзера с пагинацией
GET http://{{host}}/api/tickets/smirnovav/page/shortView?offset=0&limit=1
Authorization: Basic {{admin_login}} {{admin_password}}

###Получение списка всех тикетов конкретного юзера
GET http://{{host}}/api/tickets/smirnovav/ticket/shortView/{{sds}}
Authorization: Basic {{admin_login}} {{admin_password}}

###Получение тикета по id полной формы
GET http://{{host}}/api/tickets/4/fullView
Authorization: Basic {{admin_login}} {{admin_password}}

###Редактирование тикета по id
PATCH http://{{host}}/api/tickets
Authorization: Basic {{admin_login}} {{admin_password}}
Accept: application/json
Content-Type: application/json

{
  "id": 3,
  "code": "SHD",
  "title": "title3_EDITED",
  "description": "NEW DESCRIPTION",
  "requesterId": "smirnovav",
  "managerId": "bakinasv",
  "status": "IN_PROGRESS",
  "createdAt": "2024-01-27T12:30:00",
  "statusUpdatedAt": "2024-01-28T11:00:00",
  "controlPeriodAt": null,
  "comments": [],
  "estimation": null
}

###Создание тикета по id
POST http://{{host}}/api/tickets
Authorization: Basic {{admin_login}} {{admin_password}}
Accept: application/json
Content-Type: application/json

{
    "code": "PHD",
    "title": "NEW_PHD_TASK",
    "description": "ticket N very very very very very long description"
}

###Установить менеджера в тикет
PATCH http://{{host}}/api/tickets/5/edit/manager
Authorization: Basic {{admin_login}} {{admin_password}}
Accept: application/json
Content-Type: application/json

{
  "userId": "smirnovav",
  "managerId": "ivanovap"
}

###Удалить тикет админ
DELETE http://{{host}}/api/tickets/1
Authorization: Basic {{admin_login}} {{admin_password}}

###Удалить тикет не свой не админ
DELETE http://{{host}}/api/tickets/4
Authorization: Basic {{common_user_login}} {{common_user_password}}

###Удалить тикет свой не админ
DELETE http://{{host}}/api/tickets/2
Authorization: Basic {{admin_login}} {{admin_password}}
