services:
    db:
        image: postgres
        container_name: ticket_service_db
        environment:
            POSTGRES_DB: ticket_service
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - app:/home/node/app
        ports:
            - 8085:5432
            
    app:
        image: ticket_service_app_image
        container_name: ticket_service_app
        build:
            context: .
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticket_service
            SPRING_PROFILES_ACTIVE: prom
        ports:
            - 8083:8083
        depends_on:
            - db
            - rediscash
            - kafka
            - zookeeper

    rediscash:
        image: redis/redis-stack
        container_name: ticket_service_rediscash
        ports:
            - 6379:6379
            - 8001:8001

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - 29092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
    app: 