server:
  port: 8082

spring:
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
    properties:
        hibernate: 
            jdbc:
                time_zone: UTC+03
        
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    cache: off


ticket:
  code: SHD
  startedStatus: NEW
  SLA:
    days: 5

