server:
  port: 8083

spring:
  jpa:
    show-sql: true
    open-in-view: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    properties:
        hibernate: 
            jdbc:
                time_zone: UTC+03
    generate-ddl: false
    hibernate:
        ddl-auto: none
  sql:
    init:
        mode: always
                
  datasource:
    url: jdbc:postgresql://localhost:8085/ticket_service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache: off

  cache:
    type: redis
    redis:
      time-to-live: 10s

  data:
    redis:
      host: localhost
      port: 6379
      database: 1

  kafka:
    consumer:
      bootstrap-servers: host.docker.internal:19092
    producer:
      bootstrap-servers: host.docker.internal:19092
    topic-1: topic-1
    topic-2: topic-2
    bootstrap-servers: host.docker.internal:19092

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

ticket:
  code: SHD
  startedStatus: NEW
  SLA:
    days: 5