server:
  port: 8083

spring:
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
    properties:
        hibernate:
          jdbc:
                time_zone: UTC+03
          format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 6000

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache: off

  data:
    redis:
      host: localhost
      port: 6379
      database: 1

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
    topic-1: topic-1
    topic-2: topic-2
    bootstrap-servers: localhost:29092



ticket:
  code: SHD
  startedStatus: NEW
  SLA:
    days: 5

